// This file was autogenerated by print_selective_registration_header.py
#ifndef OPS_TO_REGISTER
#define OPS_TO_REGISTER

    namespace {
      constexpr const char* skip(const char* x) {
        return (*x) ? (*x == ' ' ? skip(x + 1) : x) : x;
      }

      constexpr bool isequal(const char* x, const char* y) {
        return (*skip(x) && *skip(y))
                   ? (*skip(x) == *skip(y) && isequal(skip(x) + 1, skip(y) + 1))
                   : (!*skip(x) && !*skip(y));
      }

      template<int N>
      struct find_in {
        static constexpr bool f(const char* x, const char* const y[N]) {
          return isequal(x, y[0]) || find_in<N - 1>::f(x, y + 1);
        }
      };

      template<>
      struct find_in<0> {
        static constexpr bool f(const char* x, const char* const y[]) {
          return false;
        }
      };
    }  // end namespace
    constexpr const char* kNecessaryOpKernelClasses[] = {
"BinaryOp<CPUDevice, functor::add<float>>",
"BinaryOp<CPUDevice, functor::add<int32>>",
"ArgMaxOp<CPUDevice, float, int32>",
"BiasOp<CPUDevice, float>",
"CpuCastOp",
"ConcatV2Op<CPUDevice, ::tensorflow::int32>",
"ConcatV2Op<CPUDevice, ::tensorflow::int64>",
"ConcatV2Op<CPUDevice, float>",
"ConstantOp",
"Conv2DOp<CPUDevice, float>",
"Conv2DCustomBackpropInputOp<CPUDevice, float>",
"CropAndResizeOp<CPUDevice, float>",
"DenseToDenseSetOperationOp<int32>",
"EnterOp",
"BinaryOp<CPUDevice, functor::equal_to<int32>>",
"ExitOp",
"UnaryOp<CPUDevice, functor::exp<float>>",
"ExpandDimsOp<int32>",
"GatherNdOp<CPUDevice, float, int32>",
"GatherOp<CPUDevice, ::tensorflow::int32, int32>",
"GatherOp<CPUDevice, float, int32>",
"BinaryOp<CPUDevice, functor::greater<int32>>",
"IdentityOp",
"BinaryOp<CPUDevice, functor::less<int32>>",
"UnaryOp<CPUDevice, functor::log<float>>",
"LoopCondOp",
"MatMulOp<CPUDevice, float, false >",
"ReductionOp<CPUDevice, float, int32, Eigen::internal::MaxReducer<float>>",
"MaxPoolingOp<CPUDevice, float>",
"BinaryOp<CPUDevice, functor::maximum<float>>",
"BinaryOp<CPUDevice, functor::maximum<int32>>",
"MergeOp",
"BinaryOp<CPUDevice, functor::minimum<float>>",
"BinaryOp<CPUDevice, functor::minimum<int32>>",
"BinaryOp<CPUDevice, functor::mul<float>>",
"BinaryOp<CPUDevice, functor::mul<int32>>",
"NextIterationOp",
"NoOp",
"NonMaxSuppressionV2Op<CPUDevice, float>",
"PackOp<CPUDevice, ::tensorflow::int32>",
"PackOp<CPUDevice, float>",
"PadOp<CPUDevice, float, int32>",
"PadOp<CPUDevice, ::tensorflow::int32, int32>",
"PlaceholderOp",
"RangeOp<::tensorflow::int32>",
"BinaryOp<CPUDevice, functor::div<float>>",
"ReluOp<CPUDevice, float>",
"ReshapeOp",
"ResizeNearestNeighborOp<CPUDevice, float>",
"UnaryOp<CPUDevice, functor::round<float>>",
"UnaryOp<CPUDevice, functor::rsqrt<float>>",
"ShapeOp<int32>",
"UnaryOp<CPUDevice, functor::sigmoid<float>>",
"SoftmaxOp<CPUDevice, float>",
"SparseToDense<::tensorflow::int32, int64>",
"SplitOpCPU<float>",
"UnaryOp<CPUDevice, functor::sqrt<float>>",
"SqueezeOp",
"IdentityOp",
"StridedSliceOp<CPUDevice, ::tensorflow::int32>",
"StridedSliceOp<CPUDevice, ::tensorflow::int64>",
"StridedSliceOp<CPUDevice, float>",
"BinaryOp<CPUDevice, functor::sub<float>>",
"BinaryOp<CPUDevice, functor::sub<int32>>",
"ReductionOp<CPUDevice, float, int32, Eigen::internal::SumReducer<float>>",
"SwitchOp",
"TensorArrayPackOrGatherOp<CPUDevice, ::tensorflow::int32, false >",
"TensorArrayReadOp<CPUDevice, ::tensorflow::int32>",
"TensorArrayUnpackOrScatterOp<CPUDevice, ::tensorflow::int32, false >",
"TensorArraySizeOp",
"TensorArrayOp",
"TensorArrayWriteOp<CPUDevice, ::tensorflow::int32>",
"TopK<CPUDevice, ::tensorflow::int32>",
"TopK<CPUDevice, float>",
"UniqueOp<::tensorflow::int32, int32>",
"WhereCPUOp<bool>",
"RecvOp",
"SendOp",
};
#define SHOULD_REGISTER_OP_KERNEL(clz) (find_in<sizeof(kNecessaryOpKernelClasses) / sizeof(*kNecessaryOpKernelClasses)>::f(clz, kNecessaryOpKernelClasses))

constexpr inline bool ShouldRegisterOp(const char op[]) {
  return false
     || isequal(op, "Add")
     || isequal(op, "ArgMax")
     || isequal(op, "BiasAdd")
     || isequal(op, "Cast")
     || isequal(op, "ConcatV2")
     || isequal(op, "Const")
     || isequal(op, "Conv2D")
     || isequal(op, "Conv2DBackpropInput")
     || isequal(op, "CropAndResize")
     || isequal(op, "DenseToDenseSetOperation")
     || isequal(op, "Enter")
     || isequal(op, "Equal")
     || isequal(op, "Exit")
     || isequal(op, "Exp")
     || isequal(op, "ExpandDims")
     || isequal(op, "GatherNd")
     || isequal(op, "GatherV2")
     || isequal(op, "Greater")
     || isequal(op, "Identity")
     || isequal(op, "Less")
     || isequal(op, "Log")
     || isequal(op, "LoopCond")
     || isequal(op, "MatMul")
     || isequal(op, "Max")
     || isequal(op, "MaxPool")
     || isequal(op, "Maximum")
     || isequal(op, "Merge")
     || isequal(op, "Minimum")
     || isequal(op, "Mul")
     || isequal(op, "NextIteration")
     || isequal(op, "NoOp")
     || isequal(op, "NonMaxSuppressionV2")
     || isequal(op, "Pack")
     || isequal(op, "Pad")
     || isequal(op, "PadV2")
     || isequal(op, "Placeholder")
     || isequal(op, "Range")
     || isequal(op, "RealDiv")
     || isequal(op, "Relu")
     || isequal(op, "Reshape")
     || isequal(op, "ResizeNearestNeighbor")
     || isequal(op, "Round")
     || isequal(op, "Rsqrt")
     || isequal(op, "Shape")
     || isequal(op, "Sigmoid")
     || isequal(op, "Softmax")
     || isequal(op, "SparseToDense")
     || isequal(op, "Split")
     || isequal(op, "Sqrt")
     || isequal(op, "Squeeze")
     || isequal(op, "StopGradient")
     || isequal(op, "StridedSlice")
     || isequal(op, "Sub")
     || isequal(op, "Sum")
     || isequal(op, "Switch")
     || isequal(op, "TensorArrayGatherV3")
     || isequal(op, "TensorArrayReadV3")
     || isequal(op, "TensorArrayScatterV3")
     || isequal(op, "TensorArraySizeV3")
     || isequal(op, "TensorArrayV3")
     || isequal(op, "TensorArrayWriteV3")
     || isequal(op, "TopKV2")
     || isequal(op, "Unique")
     || isequal(op, "Where")
     || isequal(op, "_Recv")
     || isequal(op, "_Send")
  ;
}
#define SHOULD_REGISTER_OP(op) ShouldRegisterOp(op)

#define SHOULD_REGISTER_OP_GRADIENT false
#endif
